### PR TITLE
Config changes to reflect the default branch from master to main. Please merge to complete the default branch renaming job.

### PR DESCRIPTION
**Pull request by v-alje**
Auto branch renaming content.

### CODE REVIEW

**Comment by v-alje** [comment]
Docs Build status updates of commit _[4124bc6](https://github.com/dotnet/iot-api-docs/commits/4124bc618a26b8e930f3a25dbe1f748ba5eefcb9)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[iot-api-docs/xml/Iot.Device.Board/RaspberryPiBoard.xml](https://github.com/dotnet/iot-api-docs/blob/branch-renaming-2022-04-07-07-57-12/iot-api-docs/xml/Iot.Device.Board/RaspberryPiBoard.xml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/dotnet/api/iot.device.board.raspberrypiboard?view=iot-dotnet-1.5&branch=pr-en-us-21) | [Details](#user-content-a0f56d6b57f8d36e0a89dfa86017d2aa-67dda860)
[.openpublishing.publish.config.json](https://github.com/dotnet/iot-api-docs/blob/branch-renaming-2022-04-07-07-57-12/.openpublishing.publish.config.json) | :white_check_mark:Succeeded | |

<a id="a0f56d6b57f8d36e0a89dfa86017d2aa-67dda860"></a>
### [iot-api-docs/xml/Iot.Device.Board/RaspberryPiBoard.xml](https://github.com/dotnet/iot-api-docs/blob/branch-renaming-2022-04-07-07-57-12/iot-api-docs/xml/Iot.Device.Board/RaspberryPiBoard.xml)
 - **Line 0, Column 0**: **[Warning: xref-not-found]** `````Cross reference not found: 'System.MarshalByRefObject.Dispose(System.Boolean)'.`````
 - **Line 0, Column 0**: **[Warning: xref-not-found]** `````Cross reference not found: 'System.MarshalByRefObject.Dispose(System.Boolean)'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C7%5Ca633356b-29ce-6942-cb1f-c3e858f37218%5CPullRequest%5C202204070757157171-21%5Cworkflow_report.html?sv=2020-08-04&se=2022-05-08T07%3A59%3A10Z&sr=b&sp=r&sig=BGhpo2U3qwJ1os6jAf1LNda%2FpbuYxr9DXlgU%2F0Atyzk%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/a633356b-29ce-6942-cb1f-c3e858f37218?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Comment by v-alje** [comment]
@herohua Are you sure you want to make this change now? The https://github.com/Microsoft/templates.docs.msft repo doesn't have a main branch at the moment.

**Comment by Khairunj** [comment]
@v-alje Alma we are doing the templates repo line item master to main now first in config so when the support from master is removed from the code base nothing breaks.  This change will not break anything because we don have fallback logic in place at the platform level so currently both main and master is working.

**Review by gewarren — APPROVED** [review]

**Comment by v-alje** [comment]
@gewarren Thank you!

**Pull request merged**
